### ISSUE TITLE
Not working inside ion-modal-view

### ISSUE THREAD

**Issue by Lomejook** [artemdemo/morphing-carousel-ionic#1]
that white line is the morph-carousel
when I use the same code but inside ion-view everything works fine

![error-wheel-modal](https://cloud.githubusercontent.com/assets/8918952/9537506/fea6c7ee-4ced-11e5-8a44-529faf4b40d1.png)

(sorry for bad english)

**Comment by artemdemo** [comment]
Well, yeah, you're right and the problem is that I can't get carousels size, case modal is in "virtual state" before opening. I will look into it.

**Comment by artemdemo** [comment]
Ok, I think we have soluton here.

In case you're using carousel in modal you will need to update it after opening modal. Use 'identifier' attribute in order to access relevant carousel.

```html
<morph-carousel data-items="items" on-selected="selectedItem" identifier="modal-carousel" show-value="number"></morph-carousel>
```

You can update it by using helper factory $morphCarousel. Just inject it into controller and use update() method.

```javascript
$scope.openModal = function() {
  $scope.modal.show();
  $morphCarousel.update('modal-carousel');
};
```

**Comment by Lomejook** [comment]
Thanks, now its working on localhost web browser.

But i tested on iOS 7.1.2 and this happens
![img_0992](https://cloud.githubusercontent.com/assets/8918952/9622264/80bf2992-50e5-11e5-8a66-a565aa476289.PNG)

**Comment by artemdemo** [comment]
Can you please send me code of your application ("www" folder) to my email artemdemo@gmail.com ?
I want to take a look.

**Comment by yongquanben** [comment]
It seems like the morph-carousel is not rendered properly in the ion-modal-view when you go back and forward to the same page, followed by launching the ion-modal-view.

Possible to help?
