### ISSUE TITLE
How I can know if the Carousel changed his value?

### ISSUE THREAD

**Issue by JoxieMedina** [artemdemo/morphing-carousel-ionic#2]
Great plugin..!!, I have a question: How I can know if the Carousel changed his value?, Like the "on-slide-changed" from an "ion-slide-box", thanks in advance

**Comment by artemdemo** [comment]
Well, you have on-selected="selectedItem" in directive, therefore you can add watcher on this variable, something like

```javascript
$scope.$on('selectedItem', function(newValue, oldValue){
  // "selectedItem" was changed
});
```

**Comment by JoxieMedina** [comment]
Thanks, is working :dart:

**Comment by artemdemo** [comment]
I'm glad! If you can also rate my plugin I'd appreciate it :smiley:

**Comment by JoxieMedina** [comment]
Of course, Thanks again for your support :+1:
