### ISSUE TITLE
selectedItem not being updated

### ISSUE THREAD

**Issue by jenlai1345** [artemdemo/morphing-carousel-ionic#4]
Hi,

I added a watcher to watch when the carousel slide changes.
$scope.$watch('selectedItem', function(newVal,oldVal){
    alert(newVal + ',' + oldVal);
});

However, when I slide the carousel, this function never kicks off and selectedItem remains unchanged. 
This function only kicks off once initially when I load the webpage (when my js code initially set 
selectedItem = items[2]; )

Is there something that I'm doing wrong? I'm trying to find codes in morphCarousel.js that sets selectedItem when the carousel is slided, but I'm not sure where....

Any help is deeply appreciated!

**Comment by artemdemo** [comment]
Yea, you are not working in the right way with the scope of your controller.
You should do it like this:

```javascript
$scope.data = {
        selectedItem: $scope.items[2]
};

$scope.$watch('data.selectedItem', function(newValue){
        console.log(newValue);
});
```

```html
<morph-carousel data-items="items" on-selected="data.selectedItem" show-value="number"></morph-carousel>
```
