### ISSUE TITLE
how to fire event or call scope function when selected change

### ISSUE THREAD

**Issue by firaskudsy** [artemdemo/morphing-carousel-ionic#6]
how can call a scope function or fire an even when the selected value changed ?i tried the $watch on the scope selected item , but it didnt work, any help ? its urgent

**Comment by nthansen** [comment]
Hope you figured it out, if not I'll show you what I did. In my activate function, I put         
        $scope.$watch(
            function () {
                return (vm.selectedItem);
            },
            function (newValue) {
                if (newValue !== undefined) {
                    vm.selectedItem= newValue;
                }
            });

then in the morph-carousel I put on-selected="vm.selectedItem"
